---
version: '3'
services: 
  music_console:
    build: .
    command: npm run debug
    ports: 
      - 3000:3000
      - 9229:9229 # enabled for debugger
    volumes:
      - ./:/usr/src/app/
    environment: 
      MUSIC_PATH: /usr/src/app/src/express/public/music/
      